version: "3.9"

services:

  pg:
    image: postgres:16.1
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ps-net

  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web
    environment:
      RAILS_ENV: production
      TZ: Europe/Moscow
    depends_on:
      - pg
    ports:
      - '80:3000'
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - node_modules:/app/node_modules
    networks:
      - ps-net
    restart: "unless-stopped"

volumes:
  db_data:
  node_modules:

networks:
  ps-net:
