name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Load yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Load assets Cache
        id: assets-cache
        uses: actions/cache@v3
        with:
          path: public/assets
          key: ${{ runner.os }}-assets-${{ hashFiles('app/assets/**') }}-${{ hashFiles('app/channels/**') }}-${{ hashFiles('app/javascript/**') }}

      - name: Install npm packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing npm packages..."
          yarn install

      - name: Compile assets
        if: steps.assets-cache.outputs.cache-hit != 'true'
        run: |
          echo "Precompiling assets..."
          bundle exec rails assets:precompile

      - name: Save workspace
        run: |
          echo "Compressing workspace..."
          mkdir artefacts
          tar -zcf artefacts/workspace.tar.gz --exclude=./artefacts .

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace.tar.gz
          path: artefacts/workspace.tar.gz
          retention-days: 1

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    needs: build
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ps_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace.tar.gz

      - name: Extract workspace
        run: tar zxf workspace.tar.gz

      - name: RSpec
        uses: ./.github/workflows/rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://user:password@localhost:5432/ps_test"
