name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build environment
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: ps_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    container:
      image: ruby:3.2.2-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          apk add --no-cache postgresql-client

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          apk add --no-cache \
            build-base \
            postgresql-dev \
            postgresql-client \
            tzdata \
            yarn \
            git \
            chromium \
            chromium-chromedriver \
            tar \
            && rm -rf /var/cache/apk/*

      - name: Build App
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://admin:admin@postgres:5432/ps_test"
          PRODUCT_SETTINGS_PATH: ${{ github.workspace }}/product-settings.yml
        run: |
          gem install bundler
          bundle install
          bundle exec rails db:setup
          bundle exec rails db:migrate
          yarn install
          bundle exec rails assets:precompile

      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://admin:admin@postgres:5432/ps_test"
          PRODUCT_SETTINGS_PATH: ${{ github.workspace }}/product-settings.yml
        run: |
          bundle exec rspec --format documentation
          bundle exec cucumber
